version: "3"
services:
  php-fpm:
    build: ./modules/php-fpm
    volumes:
    - ./domain:/var/www/html
    - ./config/php.ini:/usr/local/etc/php/php.ini

  rabbitmq:
    build:
      context: ./modules/rabbit
    ports:
    - 5672:5672
    - 15692:15692
    - 15672:15672

  nginx:
    image: nginx
    volumes:
    - ./domain:/var/www/html
    - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80